name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create env file
        run: |
          touch .env
          echo VITE_SERVICE_URL=${{ secrets.SERVICE_URL }} >> .env
          cat .env

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Clear current folder
        uses: fifsky/ssh-action@master
        with:
          command: rm -r `ls`
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          pass: ${{ secrets.REMOTE_PASSWORD }}

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          strip_components: 1
          source: "dist/"
